module.exports = {
	name: {
		address:           '地址',
		picture:           '图片',
		phone:             '电话',
		button:            '按钮',
		text:              '文本',
		letter:            '字母',
		floor:             '楼层',
		catg:              '分类',
		page:              '分页',
		reset:             '重置',
		time:              '日期时间',
		weather:           '天气',
		weatherLogo:       '天气LOGO',
		video:             '视频',
		map2D:             '2D地图',
		web:               '网页',
		html:              '组件上传',
		swiperImage:       '轮播图',
		listByStore:       '列表',
		wonderfulActivity: '精彩活动',
		dateWeather:       '日期天气',
		navigation:        '导航列表',
		navigationFloat:   '悬浮导航',
		splitLine:         '分割线',
		storeList:         '店铺列表',
		storeDetails:      '店铺详情',
		storeInstro:       '店铺简介',
		storeInstroTitle     : '店铺简介-标题',
		storeInstroInstroduce: '店铺简介-详情',
		storeWonderful       : '店铺简介-轮播',
		storeSplitLine       : '店铺简介-竖线',
		instroTitle          : '店铺详情-标题',
		instroPicture        : '店铺详情-LOGO',
		instroButton         : '店铺详情-前往'
	},
	num: {
		address:           0,
		picture:           0,
		phone:             0,
		button:            0,
		text:              0,
		letter:            0,
		floor:             0,
		catg:              0,
		page:              0,
		reset:             0,
		time:              0,
		weather:           0,
		weatherLogo:       0,
		video:             0,
		map2D:             0,
		web:               0,
		html:              0,
		swiperImage:       0,
		listByStore:       0,
		wonderfulActivity: 0,
		dateWeather:       0,
		navigation:        0,
		navigationFloat:   0,
		splitLine:         0,
		storeList:         0,
		storeDetails:      0,
		storeInstro:       0,
		storeInstroTitle     : 0,
		storeInstroInstroduce: 0,
		storeWonderful       : 0,
		storeSplitLine       : 0,
		instroTitle          : 0,
		instroPicture        : 0,
		instroButton         : 0
	}
}