module.exports = {
	name: {
		picture:           '图片',
		text:              '文本',
		letter:            '字母',
		floor:             '楼层',
		catg:              '分类',
		page:              '分页',
		reset:             '重置',
		time:              '日期时间',
		weather:           '天气',
		weatherLogo:       '天气LOGO',
		video:             '视频',
		map2D:             '2d地图',
		listByStore:       '列表',
		wonderfulActivity: '精彩活动',
		dateWeather:       '日期天气',
		navigation:        '导航列表',
		navigationFloat:   '悬浮导航',
		splitLine:         '分割线',
		storeList:         '店铺列表',
		storeDetails:      '店铺详情',
		storeInstro:       '店铺简介'
	},
	num: {
		picture:           0,
		text:              0,
		letter:            0,
		floor:             0,
		catg:              0,
		page:              0,
		reset:             0,
		time:              0,
		weather:           0,
		weatherLogo:       0,
		video:             0,
		map2D:             0,
		listByStore:       0,
		wonderfulActivity: 0,
		dateWeather:       0,
		navigation:        0,
		navigationFloat:   0,
		splitLine:         0,
		storeList:         0,
		storeDetails:      0,
		storeInstro:       0
	}
}