module.exports = {
	name: {
		address:            '地址',
		picture:            '图片',
		phone:              '电话',
		button:             '按钮',
		buttonStatus:       '状态按钮',
		buttonAuto:         '自执行按钮',
		buttonLanguage:     '语言按钮',
		eventTrigger:       '事件触发器',
		audio:              '音频',
		text:               '文本',
		letter:             '字母',
		floor:              '楼层',
		catg:               '分类',
		page:               '分页',
		reset:              '重置',
		time:               '日期时间',
		weather:            '天气',
		weatherLogo:        '天气LOGO',
		video:              '视频',
		map2D:              '2D地图',
		web:                '网页',
		html:               '组件上传',
		swiperImage:        '轮播图',
		swiperImgAndVideo:  '图片/视频', 
		listByStore:        '店铺列表-列表',
		wonderfulActivity:  '精彩活动',
		wonderfulActivity2: '精彩活动',
		catgByActivity2:    '精彩活动分类',
		listByActivity2:    '精彩活动列表',
		resetByActivity2:   '精彩活动重置',
		dateWeather:        '日期天气',
		navigation:         '导航列表',
		navigationFloat:    '悬浮导航',
		// splitLine:          '分割线',
		storeList:          '店铺列表',
		storeDetails:       '店铺详情',
		storeInstro:        '店铺简介',
		storeInstroTitle:      '店铺简介-标题',
		storeInstroInstroduce: '店铺简介-详情',
		storeWonderful:        '店铺简介-轮播',
		storeSplitLine:        '店铺简介-竖线',
		instroTitle:           '店铺详情-标题',
		instroPicture:         '店铺详情-LOGO',
		instroButton:          '店铺详情-前往',
		// goodsList:         '商品列表',
		// listByGoods:       '商品列表-列表',
		// swiperByGoods:     '商品轮播',
		// catgByGoods:       '商品分类',
		// resetByGoods:      '商品重置',
		pictureBind:       '图片绑定',
		textBind:          '文本绑定',
		swiperBind:        '轮播绑定',
		// goodsDetails:      '商品详情',
		area:              '区域色块',
		// pictureListBind:   '图片列表绑定',
		// goodsBar:          '商品条',
		// goodsBlock:        '商品信息',
		tabs:              '标签切换',
		catgByTabs:        '分类',
		childElement:      '子元素',
		storeList2:        '店铺列表',
		storeDetails2:     '店铺详情',
		listByStore2:      '店铺列表-列表',
		catgByStore2:      '店铺分类',
		storeBlock:        '店铺信息',
		pageByStore2:      '店铺分页',
		floorByStore2:     '店铺楼层',
		buildByStore2:     '店铺楼栋',
		letterByStore2:    '店铺字母',
		resetByStore2:     '店铺重置',
		mapByStore2:       '楼层地图',
		navByStore2:       '地图导航',
		qrcode:            '二维码',
		qrcodeBind:        '二维码绑定',
		qrcodeHui:         '惠码',
		qrcodeNav:         '导航码',
		voice:             '语音助手',
		listByVoice:       '语音助手-列表',
	},
	num: {
		address:               0,
		picture:               0,
		phone:                 0,
		button:                0,
		buttonStatus:          0,
		buttonAuto:            0,
		buttonLanguage:        0,
		eventTrigger:          0,
		audio:                 0,
		text:                  0,
		letter:                0,
		floor:                 0,
		catg:                  0,
		page:                  0,
		reset:                 0,
		time:                  0,
		weather:               0,
		weatherLogo:           0,
		video:                 0,
		map2D:                 0,
		web:                   0,
		html:                  0,
		swiperImage:           0,
		swiperImgAndVideo:     0, 
		listByStore:           0,
		wonderfulActivity:     0,
		wonderfulActivity2:    0,
		catgByActivity2:       0,
		listByActivity2:       0,
		resetByActivity2:      0,
		dateWeather:           0,
		navigation:            0,
		navigationFloat:       0,
		// splitLine:             0,
		storeList:             0,
		storeDetails:          0,
		storeInstro:           0,
		storeInstroTitle:      0,
		storeInstroInstroduce: 0,
		storeWonderful:        0,
		storeSplitLine:        0,
		instroTitle:           0,
		instroPicture:         0,
		instroButton:          0,
		// goodsList:             0,
		// listByGoods:           0,
		// swiperByGoods:         0,
		// catgByGoods:           0,
		// resetByGoods:          0,
		pictureBind:           0,
		textBind:              0,
		swiperBind:            0,
		// goodsDetails:          0,
		area:                  0,
		// pictureListBind:       0,
		// goodsBar:              0,
		// goodsBlock:            0,
		tabs:                  0,
		childElement:          0,
		catgByTabs:            0,
		storeList2:            0,
		storeDetails2:         0,
		listByStore2:          0,
		catgByStore2:          0,
		storeBlock:            0,
		pageByStore2:          0,
		floorByStore2:         0,
		buildByStore2:         0,
		letterByStore2:        0,
		resetByStore2:         0,
		mapByStore2:           0,
		navByStore2:           0,
		qrcode:                0,
		qrcodeBind:            0,
		qrcodeHui:             0,
		qrcodeNav:             0,
		listByVoice:           0,
		voice:                 0,
	}
}