// 全局变量
module.exports = {
	styleMap:       require('./styleMap'),
	contentMap:     require('./contentMap'),
	compMap:        require('./compMap'),
	composeTypeMap: require('./composeTypeMap'),
	styleMAuth:     require('./styleManageAuth'),
	animeCompMap:   require('./animeCompMap'),
	animePageMap:   require('./animePageMap'),
	fieldMap:       require('./fieldMap'),
	mock:           require('./mock'),
	childElementActiveMap: require('./childElementActiveMap'),
	contentFieldFilter:    require('./contentFieldFilter'),
	statusAuth:            require('./statusAuth'),
	statusRemoveAuth:      require('./statusRemoveAuth'),
	statusAddAuth:         require('./statusAddAuth'),
	// statusManage:   require('./statusManage'),
	languages:      require('./languages'),
	tags:           require('./tags'),
}