// 父组件
module.exports = {
	activity:           1,
	picture:            1,
	web:                1,
	video:              1,
	text:               1,
	button:             1,
	swiperImage:        1,
	swiperImgAndVideo:  1,
	swiperIV:           1,
	wonderfulActivity:  1,
	wonderfulActivity2: 1,
	time:               1,
	weather:            1,
	navigation:         1,
	navigationFloat:    1,
	storeList:          1,
	storeDetails:       1,
	storeInstro:        1,
	dateWeather:        1,
	map2D:              1,
	map3D:              1,
	html:               1,
	area:               1,
	buttonStatus:       1,
	audio:              1,
	tabs:               1,
	// goodsList:          1,
	// goodsDetails:       1,
	storeList2:         1,
	storeDetails2:      1,
	qrcode:             1,
	qrcodeHui:          1,
	qrcodeNav:          1,
	qrcodeBarrage:      1,
	voice:              1,
	buttonLanguage:     1,
	biubiubiu:          1,
	advancedIV:         1,
}  